# Generated by Django 6.1.1 on 2026-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('WORKSPACE_CREATED', 'Workspace Created'), ('MEMBER_INVITED', 'Member Invited'), ('EDITING', 'editing'), ('NOTE_CREATED', 'Note Created')], max_length=50),
        ),
    ]
