# Generated by Django 6.1.1 on 2026-10-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_note_search_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private (only me)'), ('SHARED', 'Shared with the workspace')], default='PRIVATE', max_length=10),
        ),
    ]
